# Generated by Django 5.2.9 on 2026-01-16 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuyBackServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('desc', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.BigIntegerField(default=0)),
                ('station_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('unique_id', models.AutoField(primary_key=True, serialize=False)),
                ('character_id', models.BigIntegerField(default=0)),
                ('character_name', models.CharField(max_length=255)),
                ('access_token', models.TextField(default='')),
                ('refresh_token', models.CharField(max_length=100)),
                ('expiration', models.DateTimeField(blank=True, null=True)),
                ('corp_id', models.BigIntegerField(default=0)),
                ('corp_name', models.CharField(default='', max_length=255)),
                ('alliance_id', models.BigIntegerField(default=0)),
                ('alliance_name', models.CharField(default='', max_length=255)),
                ('wallet_money', models.BigIntegerField(default=0)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BuyBackProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('tax', models.BigIntegerField(default=0)),
                ('freighter_tax', models.BigIntegerField(default=0)),
                ('settings', models.ManyToManyField(related_name='program_services', to='buyback.buybackservices')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='program_location', to='buyback.location')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='program_manager', to='buyback.manager')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramSpecialTax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.BigIntegerField(default=0)),
                ('item_name', models.CharField(max_length=255)),
                ('special_tax', models.BigIntegerField(default=0)),
                ('is_allowed', models.BooleanField(default=False)),
                ('program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='program_special_taxes', to='buyback.buybackprogram')),
            ],
        ),
    ]
