# Generated by Django 5.2.9 on 2026-01-06 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuyBackServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('desc', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BuyBackProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('tax', models.BigIntegerField(default=0)),
                ('manager', models.CharField(max_length=200)),
                ('freighter_task', models.BigIntegerField(default=0)),
                ('settings', models.ManyToManyField(related_name='program_services', to='buyback.buybackservices')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='program_location', to='buyback.location')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramSpecialTax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.BigIntegerField(default=0)),
                ('item_name', models.CharField(max_length=255)),
                ('special_tax', models.BigIntegerField(default=0)),
                ('is_allowed', models.BooleanField(default=False)),
                ('program', models.ManyToManyField(related_name='special_taxes', to='buyback.buybackprogram')),
            ],
        ),
    ]
