# Generated by Django 5.2.9 on 2026-02-05 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyback', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='wallet_money',
        ),
    ]
