# Generated by Django 5.2.9 on 2026-01-06 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyback', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='name',
            new_name='station_name',
        ),
        migrations.AddField(
            model_name='location',
            name='station_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
