# Generated by Django 5.2.9 on 2026-02-06 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyback', '0002_remove_manager_wallet_money'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_id', models.CharField(max_length=254)),
                ('status', models.PositiveBigIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('program_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program', to='buyback.buybackprogram')),
            ],
        ),
    ]
