# Generated by Django 5.2.9 on 2026-01-08 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyback', '0002_rename_name_location_station_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('character_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('character_name', models.CharField(max_length=255)),
                ('access_token', models.TextField(default='')),
                ('refresh_token', models.CharField(max_length=100)),
                ('expiration', models.DateTimeField(blank=True, null=True)),
                ('corp_id', models.BigIntegerField(default=0)),
                ('corp_name', models.CharField(default='', max_length=255)),
                ('alliance_id', models.BigIntegerField(default=0)),
                ('alliance_name', models.CharField(default='', max_length=255)),
                ('wallet_money', models.BigIntegerField(default=0)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='buybackprogram',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='program_manager', to='buyback.manager'),
        ),
    ]
