# Generated by Django 5.2.5 on 2026-01-08 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyback', '0003_manager_alter_buybackprogram_manager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buybackprogram',
            old_name='freighter_task',
            new_name='freighter_tax',
        ),
    ]
