# Generated by Django 5.2.9 on 2026-02-07 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyback', '0003_contract'),
        ('sso', '0002_remove_charactereve_wallet_money'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='program_id',
            new_name='program',
        ),
        migrations.AddField(
            model_name='contract',
            name='character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='sso.charactereve'),
        ),
    ]
