# Generated by Django 5.2.9 on 2026-01-10 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyback', '0004_rename_freighter_task_buybackprogram_freighter_tax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programspecialtax',
            name='program',
        ),
    ]
