# Generated by Django 5.2.9 on 2026-01-10 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyback', '0005_remove_programspecialtax_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='programspecialtax',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='program_special_taxes', to='buyback.buybackprogram'),
        ),
    ]
