# Generated by Django 5.2.9 on 2026-02-02 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpitem',
            name='loc_flag',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='corpitem',
            name='location',
            field=models.TextField(default=''),
        ),
    ]
