# Generated by Django 5.2.9 on 2026-02-06 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_corpitem_loc_flag_corpitem_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corpitem',
            name='location',
        ),
    ]
