# Generated by Django 5.2.9 on 2026-02-02 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='contract_id',
        ),
    ]
