# Generated by Django 5.2.9 on 2026-01-03 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterEve',
            fields=[
                ('character_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('character_name', models.CharField(max_length=255)),
                ('main_character', models.BooleanField(default=False)),
                ('access_token', models.TextField(default='')),
                ('refresh_token', models.CharField(max_length=100)),
                ('expiration', models.DateTimeField(blank=True, null=True)),
                ('corp_id', models.BigIntegerField(default=0)),
                ('corp_name', models.CharField(default='', max_length=255)),
                ('alliance_id', models.BigIntegerField(default=0)),
                ('alliance_name', models.CharField(default='', max_length=255)),
                ('wallet_money', models.BigIntegerField(default=0)),
                ('deleted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='characters_eve', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
